# Cloudflare Pages Configuration
# For Tyler's Tech Tips Platform

name = "tylers-tech-tips"
compatibility_date = "2025-10-29"
pages_build_output_dir = "."
compatibility_flags = ["nodejs_compat"]

# Bindings are configured in Cloudflare Pages dashboard
# This file should NOT contain binding configuration for Pages

