# Cloudflare Pages Configuration
# For Tyler's Tech Tips Platform

name = "tylers-tech-tips"
compatibility_date = "2025-10-29"
pages_build_output_dir = "."
compatibility_flags = ["nodejs_compat"]

# D1 Database Bindings (Already configured in Cloudflare Pages)
# DB → community_db
# TYLERS_TECH_DB → community_db

# KV Namespace Bindings (Already configured in Cloudflare Pages)
# TYLERS_TECH_KV → ttt-rate-limit
# RATE_LIMIT → ttt-rate-limit

## R2 Bucket Binding (disabled for Pages; add in dashboard if needed)
# [[r2_buckets]]
# binding = "R2_BUCKET"
# bucket_name = "tylers-tech-uploads"

