# Cloudflare Pages Configuration
# For Tyler's Tech Tips Platform

name = "tylers-tech-tips"
compatibility_date = "2025-10-29"
pages_build_output_dir = "."
compatibility_flags = ["nodejs_compat"]

# D1 Database Bindings (Already configured in Cloudflare Pages dashboard)
# DB → community_db

# KV Namespace Bindings (Already configured in Cloudflare Pages dashboard)
# TYLERS_TECH_KV → ttt-rate-limit

# Note: R2, Durable Objects, and other bindings are configured in the Cloudflare dashboard
# This file is kept minimal to avoid TOML parsing issues during Pages deployment
